"""Build the site's Latin + IAST font subsets and their @font-face rules.

Fontsource ships Latin Extended as one large subset (170-230 KB per style for Noto), but the
encyclopedia needs only Latin, Latin-1 and the letters of IAST / ISO 15919. This script cuts the
Noto Serif variable fonts down to exactly that, writes woff2 files to public/fonts/ and the
matching rules to src/styles/fonts.css. Both outputs are committed; re-run the script only when
the font packages are upgraded.

    pip install fonttools brotli
    python scripts/fonts/subset-fonts.py
"""
import os

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SOURCE = os.path.join(ROOT, 'node_modules', '@fontsource-variable')
OUT = os.path.join(ROOT, 'public', 'fonts')
CSS = os.path.join(ROOT, 'src', 'styles', 'fonts.css')

IAST = 'āīūṛṝḷḹṃṁḥṅñṭḍṇśṣēōṟṉḻĀĪŪṚṜḶḸṂṀḤṄÑṬḌṆŚṢĒŌṞṈḺ'
WANTED = sorted(
    set(
        list(range(0x20, 0x7F))
        + list(range(0xA0, 0x100))
        + [0x131, 0x152, 0x153, 0x2BC, 0x2C6, 0x2DA, 0x2DC]
        + list(range(0x2010, 0x2028))
        + [0x2030, 0x2032, 0x2033, 0x2039, 0x203A, 0x2044, 0x20AC, 0x20B9, 0x2122, 0x2212]
        + [ord(char) for char in IAST]
    )
)

# (css family, source package, fontsource style suffix, css font-style)
FACES = [
    ('Noto Serif Subset', 'noto-serif', 'wght-normal', 'normal'),
    ('Noto Serif Subset', 'noto-serif', 'wght-italic', 'italic'),
    ('Noto Serif Display Subset', 'noto-serif-display', 'wght-normal', 'normal'),
]


def ranges(codes):
    """Compress code points into a CSS unicode-range list."""
    parts, start, prev = [], None, None
    for code in codes:
        if start is None:
            start = prev = code
        elif code == prev + 1:
            prev = code
        else:
            parts.append((start, prev))
            start = prev = code
    if start is not None:
        parts.append((start, prev))
    return ', '.join(f'U+{a:04X}' if a == b else f'U+{a:04X}-{b:04X}' for a, b in parts)


os.makedirs(OUT, exist_ok=True)
rules = [
    '/* Generated by scripts/fonts/subset-fonts.py — do not edit by hand. */',
    '/* Noto Serif and Noto Serif Display cut to Latin, Latin-1 and the IAST / ISO 15919 letters. */',
]
for family, package, style, css_style in FACES:
    # Fontsource splits each font into slices; subset the Latin slice for ASCII/Latin-1 and the
    # Latin Extended slice for the transliteration letters, keeping each as its own file so the
    # browser downloads the second only on pages that use diacritics.
    for slice_name, part in [('latin', 'latin'), ('latin-ext', 'iast')]:
        source = os.path.join(SOURCE, package, 'files', f'{package}-{slice_name}-{style}.woff2')
        font = TTFont(source)
        cmap = font.getBestCmap()
        codes = [code for code in WANTED if code in cmap]
        options = subset.Options()
        options.flavor = 'woff2'
        options.layout_features = ['*']
        options.name_IDs = ['*']
        options.notdef_outline = True
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=codes)
        subsetter.subset(font)
        # Italic is only ever set at the regular weight (IAST terms, verse, titles), so pin it.
        pinned = css_style == 'italic'
        if pinned:
            from fontTools.varLib import instancer

            font = instancer.instantiateVariableFont(font, {'wght': 400})
            font.flavor = 'woff2'
        file_name = f'{package}-{style}-{part}.woff2'
        font.save(os.path.join(OUT, file_name))
        size = os.path.getsize(os.path.join(OUT, file_name)) / 1024
        print(f'{file_name:44} {len(codes):4} chars {size:6.1f} KB')
        rules.append(
            '\n'.join(
                [
                    '@font-face {',
                    f"  font-family: '{family}';",
                    f'  font-style: {css_style};',
                    '  font-display: swap;',
                    f"  font-weight: {'400' if pinned else '100 900'};",
                    f"  src: url('/fonts/{file_name}') format('{'woff2' if pinned else 'woff2-variations'}');",
                    f'  unicode-range: {ranges(codes)};',
                    '}',
                ]
            )
        )

# Devanagari: the variable font's Devanagari slice is ~125 KB. Running text and names need only
# the regular weight, so pin wght to 400 (headings in Devanagari are rare and synthesise bold).
from fontTools.varLib import instancer  # noqa: E402

deva_source = os.path.join(
    SOURCE, 'noto-serif-devanagari', 'files', 'noto-serif-devanagari-devanagari-wght-normal.woff2'
)
deva = TTFont(deva_source)
deva_codes = sorted(deva.getBestCmap().keys())
deva = instancer.instantiateVariableFont(deva, {'wght': 400})
deva.flavor = 'woff2'
deva_file = 'noto-serif-devanagari-400-deva.woff2'
deva.save(os.path.join(OUT, deva_file))
print(f'{deva_file:44} {len(deva_codes):4} chars {os.path.getsize(os.path.join(OUT, deva_file)) / 1024:6.1f} KB')
rules.append(
    '\n'.join(
        [
            '@font-face {',
            "  font-family: 'Noto Serif Devanagari Subset';",
            '  font-style: normal;',
            '  font-display: swap;',
            '  font-weight: 400;',
            f"  src: url('/fonts/{deva_file}') format('woff2');",
            f'  unicode-range: {ranges(deva_codes)};',
            '}',
        ]
    )
)

with open(CSS, 'w', encoding='utf-8', newline='\n') as handle:
    handle.write('\n\n'.join(rules) + '\n')
print(f'wrote {os.path.relpath(CSS, ROOT)}')
